---
title: "Categorical change"
author: "Stefano Coretta"
date: "28/05/2017"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
theme_set(theme_bw())
library(zipfR)
library(mgcv)
library(itsadug)
options(contrasts = rep("contr.treatment", 2))
```

# Initialise

The frequency distribution is produced by the following function, `zipfDistr()`. The distribution is a random sample from a Zipfian distribution (it uses the `zipfR` package).

```{r zipfDistr}
zipfDistr <- function(size) {
    zipf.model <- lnre("zm", alpha = 2/7, B = 0.1)
    zipf.sample <- rlnre(zipf.model, n = size)
    zipf.distr <- sort(as.numeric(as.character(zipf.sample)))
    return(zipf.distr)
}
```

```{r createLexicon}
createLexicon <- function(size, frequency) {
    word <- seq(1:size)
    glot.prob <- 0
    exemplars <- 1
    lexicon <- tibble(word, frequency, glot.prob, exemplars)
    return(lexicon)
}
```

```{r simulateGlott}
simulateGlott <- function(lexicon, lexicon.size, frequency, iterations) {
    lexicon.change <- tibble("iteration" = numeric(),
                             "word" = numeric(),
                             "frequency" = numeric(),
                             "glot.prob" = numeric(),
                             "exemplars" = numeric()
                             )
    for (iteration in 1:iterations) {
        word <- sample(1:lexicon.size, 1, prob = frequency)
        previous.prob <- lexicon$glot.prob[word]
        exemplars <- lexicon$exemplars[word]
        if (previous.prob == 0) {
            is.glottalised <- sample(c(1, 0), 1, prob = c(0.5, 0.5))
        } else {
            is.glottalised <- sample(c(1, 0), 1, prob = c(previous.prob, 1-previous.prob))
        }
        

        lexicon$glot.prob[word] <- previous.prob +
            (is.glottalised / (exemplars + 1) ) -
            (previous.prob / (exemplars + 1) )
        lexicon$exemplars[word] <- exemplars + 1
        
        plot.frequency <- lexicon.size * iterations / 50000
        
        if (iteration %% plot.frequency == 0) {
            lexicon.change <- rbind(lexicon.change, cbind(iteration, lexicon))
        }
    }
    return(lexicon.change)
}
```


# Simulation

```{r}
set.seed(777)

lexicon.size <- 100
lexicon.frequency <- seq(1:lexicon.size) # try with seq()
lexicon <- createLexicon(lexicon.size, lexicon.frequency)

iterations <- 5000
lexicon.change <- simulateGlott(lexicon, lexicon.size, lexicon.frequency, iterations)

lexicon.change <- lexicon.change %>%
    mutate(
        freq.bin = ifelse(frequency < max(frequency)/2,"low","high")
    )
```

## Plotting

```{r}
lexicon.change %>%
    ggplot(aes(iteration, glot.prob, colour = freq.bin)) +
    geom_smooth()
```

```{r}
lexicon.change %>%
    ggplot(aes(iteration, glot.prob, colour = freq.bin)) +
    geom_smooth(method = "lm")
```

```{r}
lexicon.change %>%
    filter(iteration < 501) %>%
    ggplot(aes(iteration, glot.prob, colour = freq.bin)) +
    geom_smooth()
```

```{r}
lexicon.change %>%
    filter(iteration < 501) %>%
    ggplot(aes(iteration, glot.prob, colour = freq.bin)) +
    geom_smooth(method = "lm")
```

```{r}
lexicon.change %>%
    ggplot(aes(iteration, glot.prob, group = word, colour = freq.bin)) +
    geom_line(stat = "smooth", method = "loess", alpha = 0.5, se = FALSE)
```

## Analysis

```{r}
lexicon.change$word.ord <- as.ordered(lexicon.change$word)
lexicon.change <- lexicon.change %>%
    arrange(word, iteration) %>%
    start_event(column = "iteration", event = c("word"))
```

```{r}
glot.gam <- bam(
    glot.prob ~
        # frequency +
        s(frequency, bs = "cr") +
        s(iteration, bs = "cr") +
        ti(iteration, frequency, bs = "cr") +
        s(word, bs = "fs"),
    data = lexicon.change,
    method = "fREML"
)

r1 <- start_value_rho(glot.gam)

glot.gam.ar <- bam(
    glot.prob ~
        # frequency +
        s(frequency, bs = "cr") +
        s(iteration, bs = "cr") +
        ti(iteration, frequency, bs = "cr"),
    data = lexicon.change,
    method = "ML",
    rho = r1,
    AR.start = lexicon.change$start.event
)

summary(glot.gam.ar)

glot.gam.ar.null <- bam(
    glot.prob ~
        # frequency +
        s(frequency, bs = "cr") +
        s(iteration, bs = "cr"),
#        ti(iteration, frequency, bs = "cr"),
    data = lexicon.change,
    method = "ML",
    rho = r1,
    AR.start = lexicon.change$start.event
)

compareML(glot.gam.ar, glot.gam.ar.null)
```

```{r}
acf_resid(glot.gam.ar, split_pred = "AR.start")
```


```{r}
fvisgam(glot.gam.ar, view = c("iteration","frequency"))
```



# CRE

```{r}
create_lexicon_cre <- function(size) {
    iteration <- rep_len(1, size)
    word <- seq(1:size)
    frequency <- seq(1:size)
    glottalised <- "no"
    lexicon <- tibble(iteration, word, frequency, glottalised)
    return(lexicon)
}

cre <- function(size, iterations) {
    lexicon <- create_lexicon_cre(size)
    lexicon_change <- lexicon
    probability <- 0
    
    for (i in 1:iterations) {
        word <- sample(1:size, 1, prob = lexicon$frequency)
        frequency <- lexicon$frequency[word]
        
        is_glottalised <- sample(c("yes", "no"), 1, prob = c(probability, 1 - probability))
        
        current <- tibble("iteration" = i, word, frequency, "glottalised" = is_glottalised)
        
        lexicon_change <- rbind(lexicon_change, current)
        
        probability <- probability + 0.001
    }
    
    return(lexicon_change)
}
```

```{r}
set.seed(1234)
lexicon <- cre(1000, 500) %>%
    mutate(
        glottalised_prob = as.numeric(as.factor(glottalised)),
        freq_bin = ifelse(
            frequency < 500,
            "low",
            "high"
        )
    )
```

```{r}
lexicon %>%
    ggplot(aes(iteration, glottalised_prob)) +
    geom_smooth()
```

```{r}
lexicon %>%
    ggplot(aes(iteration, glottalised_prob, colour = freq_bin)) +
    geom_smooth(method = "loess", span = 100)
```
